aws_image            = "ami-07f84a50d2dec2fa4" #"ami-086c1d77a774201ee"
aws_instance         = "t2.micro"
aws_region           = "us-east-2"
aws_availability_region           = "us-east-2a"
key_pair_name        = ""
key_pair_public_key  = ""